name: Build MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Set up WiX Toolset
        run: dotnet tool install --global wix --version 5.0.1
        shell: cmd

      - name: Download binaries
        run: |
          Invoke-WebRequest -Uri "https://github.com/nextcloud-releases/talk-desktop/releases/download/v0.38.0/Nextcloud.Talk-win32-x64-0.38.0.zip" -OutFile "NextcloudTalk.zip"

      - name: Extract binaries
        run: |
          Expand-Archive -Path "NextcloudTalk.zip" -DestinationPath "NextcloudTalk"

      - name: Build MSI
        run: |
          dotnet build NextcloudTalkClient.wixproj
          
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: NextcloudTalk.msi
          path: NextcloudTalk.msi
